config/routes.rb
EliteApp::Application.routes.draw do
  resources :card_processing_upload_statuses do
    member do
      get :markings
      get :scanned
    end
  end

  resources :attendance_lists
  resources :card_processings
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'card/:student_ra/:exam_code', to: 'student_exams#card'
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'calendar/', to: 'calendar#index'

  get 'exam_executions/', to: 'exam_executions#index'
  get 'exam_executions/:exam_execution_id/result', to: 'exam_executions#result', as: 'result_exam_execution'
  get 'exam_executions/:exam_execution_id/attendance', to: 'exam_executions#attendance', as: 'attendance_exam_execution'
  get 'exam_executions/:exam_execution_id/cards', to: 'exam_executions#cards', as: 'cards_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned', to: 'exam_executions#scanned', as: 'scanned_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned_md5', to: 'exam_executions#scanned_md5', as: 'scanned_md5_exam_execution'

  resources :topics
  resources :card_types
  resources :student_exams do 
    member do 
      get :error
    end
  end
  get 'student_exams/new/', to: 'student_exams#new'

  resources :exam_answers
  resources :exams do
    collection do
      post :import
    end
  end 
  resources :questions
  resources :exam_cycles
  resources :applicants  do
    
  end
  resources :students do 
    member do 
      get :fix_ra
    end
    collection do
      post :import
    end
  end

  resources :poll_question_types
  resources :poll_question_categories
  resources :poll_pdfs
  resources :polls

  resources :teacher_absences
  resources :teacher_reports

  resources :klazz_calendars

  resources :personal_infos
  resources :professional_infos
  resources :schedule_infos

  resources :teachers do
    resources :periods, controller: 'teacher_periods'
  end
  resources :employees

  resources :absence_reasons
  resources :majors
  resources :school_roles
  resources :elite_roles
  resources :klazz_types
  resources :subjects
  resources :subject_threads

  resources :klazzes do 
    resources :periods, controller: 'klazz_periods'
  end
  
  resources :campuses do 
    resources :periods, controller: 'campuses_periods'
  end
  resources :super_klazzes 
  resources :product_years
  resources :years
  resources :products
  resources :product_groups
  resources :product_types

  get 'change_role/:role', to: 'role_sessions#update'

  match 'auth/google_oauth2/callback', to: 'employee_sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'login_as/:id', to: 'employee_sessions#update', as: 'login_as'
  match 'logout', to: 'employee_sessions#destroy', as: 'logout'

  get 'api/cards', to:'api#student_exams', as: 'api'
  get 'home', to: 'home#index', as: 'home'
  get "exam_results", to: 'exam_results#index'  
  root to: 'home#index'
end

app/models/employee.rb
# encoding: UTF-8
class Employee < ActiveRecord::Base

  GENDERS = ['Masculino', 'Feminino']
  MARITAL_STATUSES = ['Solteiro(a)', 'Casado(a)', 'Separado(a)', 'Divorciado(a)', 'Viúvo(a)']

  mount_uploader :photo, PhotoUploader
  
  attr_accessible :elite_id, :email, :roles, :chapa,
    :name, :employee_id, :address, :suburb, :city, :state, :personal_email, 
    :identification, :expeditor, :cpf, :cellphone, :alternative_cellphone, :telephone, 
    :alternative_telephone, :contact_telephone, :contact_name, :photo, :remove_photo,
    :roles, :employee_attributes, :date_of_birth, :gender, :marital_status,
    :date_of_admission, :elite_role_id, :contract_type, :workload, 
    :cost_per_hour, :pis_pasep, :working_paper_number,
    :teacher_attributes, :product_head_teacher_attributes, 
    :campus_head_teacher_attributes, :subject_head_teacher_attributes, 
    :campus_principal_attributes, :address_attributes

  belongs_to :elite_role

  with_options dependent: :destroy do |e|
    has_one :admin
    has_one :operator
    has_one :teacher
    has_one :campus_head_teacher
    # has_one :product_head_teacher
    # has_one :subject_head_teacher
    # has_one :campus_principal
    # has_one :address, as: :addressable
  end

  with_options allow_destroy: true do |e|
    e.accepts_nested_attributes_for :teacher
    e.accepts_nested_attributes_for :campus_head_teacher
    # e.accepts_nested_attributes_for :product_head_teacher
    # e.accepts_nested_attributes_for :subject_head_teacher
    # e.accepts_nested_attributes_for :campus_principal
    # e.accepts_nested_attributes_for :address
  end

  validates :email, uniqueness: true, allow_blank: true, 
    format: { with: /\A([^@\s]+)@pensi\.com\.br\z/i }
  # validates :elite_id, presence: true, uniqueness: true
  validates :name, presence: true

  # TODO: add hr role
  ROLES = %w[admin teacher campus_head_teacher operator]

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end

  def roles=(_roles)
    self.roles_mask = (_roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  ROLES.each do |role|
    define_method role + '?' do
      roles.include? role
    end
  end

  def build_roles
    (ROLES - roles).each { |role| send('build_' + role) }
  end

  def check_uid(_uid)
    if uid.nil?
      update_column :uid, _uid
    else
      logger.info "Uid from employee number #{id} changed" if _uid != uid
    end
  end

  def admin?
    roles.include? 'admin'
  end

  def remove_photo!
  end

  def self.translate_role input
    translation_hash = {
      'Admin' => 'Administrador',
      'Teacher' => 'Professor',
      'Campus head teacher' => 'Coordenador',
      'Campus Head Teacher' => 'Coordenador',
      'Operator' => 'Operador'
    }
    translation_hash[input] || 'Não Encontrado'
  end

  def self.send_email_importing_success(mail)
      ActionMailer::Base.mail(
        from: 'pensisim@pensi.com.br',
        to: email || 'pensisim@pensi.com.br',
        subject: "Envio arquivo importação de Usuários #{DateTime.now.strftime('%d/%m/%Y %H:%M')}",
        body: <<-eos
Olá,

Você acaba de enviar um arquivo para importação de usuários.

Não houveram problemas na importação.

--
PENSI Simulados
        eos
      ).deliver
  end

  def self.send_email_importing_error(errors, mail)
      ActionMailer::Base.mail(
        from: 'pensisim@pensi.com.br',
        to: email || 'pensisim@pensi.com.br',
        subject: "Envio arquivo importação de Usuários #{DateTime.now.strftime('%d/%m/%Y %H:%M')}",
        body: <<-eos
Olá,

Você acaba de enviar um arquivo para importação de usuários.

Os seguintes usuários tiveram problemas na importação:

#{errors.join('\n')}

--
PENSI Simulados
        eos
      ).deliver    
  end

  def self.import(file, email)
    errors = []
    file = file.path if file.class.to_s != 'String'
    CSV.foreach(file) do |name, email|
      begin
        p "#{name},#{email}"
        Employee.create!(
          name: name,
          email: email)
      rescue Exception => e
        errors << [name, email].join(', ')
        p 'ERRO! ' + e.message          
      end
    end

    # send email
    if errors.size > 0
      send_email_importing_error(errors, mail)
    else
      send_email_importing_success(email)
    end    
  end

end

app/controllers/employees_controller.rb
# encoding: UTF-8
class EmployeesController < ApplicationController
  load_and_authorize_resource

  def index
    @employees = @employees.includes(:teacher).all
  end

  def show
  end

  def new
    set_employee
  end

  def edit
    set_employee
  end

  def create
    if @employee.save
      redirect_to @employee, notice: 'Funcionário criado com sucesso.'
    else
      set_employee
      render 'new'
    end
  end

  def update
    if @employee.update_attributes(params[:employee]) || @employee.teacher.update_attributes(params[:teacher])
      redirect_to @employee, notice: 'Funcionário editado com sucesso.'
    else
      set_employee
      render 'edit'
    end
  end

  def import
    ExamCsvImportWorker.perform_async(params[:file].tempfile.path, current_employee.email)
    redirect_to root_url, notice: "Usuários importados com sucesso."    
  end

private

  def set_employee
    @employee.build_roles
    # @employee.build_address if @employee.address.nil?
    # @employee.teacher.build_product_group_preferences
    # @employee.teacher.professional_experiences.build if @employee.teacher.professional_experiences.empty?
  end
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>

  <div class='form-inputs'>
    <%= render 'employees/form/fields', f: f %>

    <% if current_employee.admin? %>
      <h2>Credenciais</h2>
      <%= f.input :roles, label: '', as: :check_boxes, wrapper_html: { id: 'employee_roles' }, 
        collection: Employee::ROLES.map{|x| [Employee.translate_role(x.humanize), x]} %>

      <div id='campus_head_teacher_fields'>
        <h2>Coordenador</h2>
        <%= f.simple_fields_for :campus_head_teacher do |builder| %>
          <%= render 'employees/form/campus_head_teacher_fields', f: builder %>
        <% end %>
      </div>

      <% if false %>
      <div id='product_head_teacher_fields'>
        <h2>Product Head Teacher</h2>
        <%= f.simple_fields_for :product_head_teacher do |builder| %>
          <%= render 'employees/form/product_head_teacher_fields', f: builder %>
        <% end %>
      </div>

      <div id='subject_head_teacher_fields'>
        <h2>Subject Head Teacher</h2>
        <%= f.simple_fields_for :subject_head_teacher do |builder| %>
          <%= render 'employees/form/subject_head_teacher_fields', f: builder %>
        <% end %>
      </div>

      <div id='campus_principal_fields'>
        <h2>Campus Principal</h2>
        <%= f.simple_fields_for :campus_principal do |builder| %>
          <%= render 'employees/form/campus_principal_fields', f: builder %>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>

  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/_teacher_fields.html.erb
<%= f.hidden_field :_destroy, class: 'destroy' %>
<%= f.input :nickname %>

<%= f.input :graduated, as: :radio_buttons, wrapper_html: { id: "person_graduated" } %>
<%= f.association :major %>
<%= f.input :institute, placeholder: "Ex: UFRJ" %>
<%= f.input :bachelor, as: :radio_buttons %>
<%= f.input :cref, as: :radio_buttons %>
<%= f.input :time_teaching, placeholder: "Ex: 10 anos" %>

<%= f.simple_fields_for :professional_experiences do |builder| %>
  <%= render 'professional_experience_fields', f: builder %>
<% end %>
<p class="add_field"><%= link_to_add_fields "Adicionar", f, :professional_experiences %></p>

<%= f.input :post_graduated, as: :radio_buttons, wrapper_html: { id: "employee_post_graduated" } %>
<%= f.input :post_graduated_comment, label: 'Comment' %>

<%= f.association :subjects %>

<table id='product_group_preferences'>
  <colgroup span='1'></colgroup>
  <tr>
    <th></th>
    <th>Gosto</th>
    <th>Posso dar aula</th>
    <th>Não dou aula</th>
    <% if @employee.teacher.errors.any? %>
      <th></th>
    <% end %>
  </tr>
  <%= f.simple_fields_for :product_group_preferences do |builder| %>
      <%= builder.input :preference, 
        wrapper: :table_wrapper, 
        collection: 1..3, 
        as: :radio_buttons, 
        label: builder.object.product_group.name,
        boolean_style: :inline, 
        item_wrapper_tag: :td,
        wrapper_tag: :tr %>
      <%= builder.hidden_field :product_group_id %>
      <%= builder.hidden_field :teacher_id %>
  <% end %>
</table>

<p>Escolha quais são as Unidades de sua preferência.</p>
<%= f.association :campuses, label: false,
  wrapper_html: { id: 'campus_preferences' } %>

<p>Marque a seguir a sua disponibilidade para o ano de 2013.</p>
<%= period_input f, :morning %>
<%= period_input f, :afternoon %>
<%= period_input f, :evening %>

<table id='weekend'>
  <tr>
    <td class='first'>Sábado</td>
    <td><%= f.input :saturday_moning, label: 'Manhã' %></td>
    <td><%= f.input :saturday_afternoon, label: 'Tarde' %></td>
  </tr>
  <tr>
    <td class='first'>Domingo</td>
    <td><%= f.input :sunday_morning, label: 'Manhã' %></td>
    <td><%= f.input :sunday_afternoon, label: 'Tarde' %></td>
  </tr>
</table>

<%= f.input :administrative_job, :as => :radio_buttons,
  collection: [['Sim', true], ['Não', false]], label: 'Você tem interesse em Cargos Adminstrativos?', 
  wrapper_html: { id: 'administrative_job_wrapper' } %>

app/views/employees/edit.html.erb
<%= title 'Editar Funcionário',
  link_to('Mostrar', @employee),
  link_to('Voltar', employees_path) %>

<%= render 'form' %>

app/views/employees/index.html.erb
<%= title 'Employees', 
  (link_to('New Employee', new_employee_path) if can?(:create, Employee)) %>

<table id='employees' class='display is-datatable'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roles</th>
    </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <td>
        <%= employee.name %>
        <span>
          <%= link_to 'Mostrar', employee_path(employee) %>
          <% if can?(:update, employee) %>
            | <%= link_to 'Editar', edit_employee_path(employee) %> 
          <% end %>
          <% if can?(:update, :employee_sessions) %>
            | <%= link_to 'Entrar como', login_as_path(employee) %>
          <% end %>
        </span>
      </td>
      <td><%= employee.roles.map{|role| Employee.translate_role role}.join(', ') %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<%= title 'Novo Funcionário' %>

<%= render 'form' %>

app/views/employees/show.html.erb
<%= title @employee.name, 
  (link_to('Edit', edit_employee_path(@employee)) if can?(:update, @employee)),
  link_to(t('Back'), employees_path) %>

<div id='employee_important_fields'>
  <div class='resource'>
    <p><span>Email: </span><%= @employee.email %></p>
    <p><span>Roles: </span><%= @employee.roles.map(&:titleize).join(', ') %></p>
  </div>

  <div id='photo'>
    <%= image_tag(@employee.photo_url(:thumb)) if @employee.photo? %>
  </div>
</div>

<div class='tabs'>
  <ul>
    <li><a href='#info_tab'>Info</a></li>

    <% if @employee.teacher? %>
      <li><%= link_to 'Calendário', teacher_periods_path(@employee.teacher), title: 'calendar_tab' %></li>
      <li><%= link_to 'Disponibilidade', teacher_path(@employee.teacher), title: 'availability' %></li>
    <% end %>
  </ul>

  <div id='info_tab'>
    <div class='resource'>
      <%= show_group 'Contact Info', 
        {
          'Personal Email' => @employee.personal_email,
          'Cellphone' => @employee.cellphone,
          'Alternative Cellphone' => @employee.alternative_cellphone,
          'Telephone' => @employee.telephone,
          'Alternative Telephone' => @employee.alternative_telephone,
          'Contact Telephone' => @employee.contact_telephone,
          'Contact Name' => @employee.contact_name
        }
      %>

      <% if current_employee.admin? or current_employee == @employee %>
        <% if @employee.address.present? %>
          <%= show_group 'Address',
            {
              'Street' => @employee.address.street,
              'Number' => @employee.address.number,
              'Complement' => @employee.address.complement,
              'Suburb' => @employee.address.suburb,
              'City' => @employee.address.city,
              'State' => @employee.address.state
            } 
          %>
        <% end %>

        <%= show_group 'Documents', 
          {
            'Identification Number' => @employee.identification,
            'Expeditor' => @employee.expeditor,
            'CPF' => @employee.cpf,
            'Pis/Pasep' => @employee.pis_pasep,
            'Working Paper Number' => @employee.working_paper_number,
            'Date of Birth' => @employee.date_of_birth
          }
        %>
      <% end %>

      <%= 
        # show_group 'Elite Info', 
        # {
        #   'Elite Role' => @employee.elite_role,
        #   'Workload' => @employee.workload,
        #   'Contract Type' => @employee.contract_type,
        #   'Cost per Hour' => @employee.cost_per_hour.to_s
        # }
      %>
    </div>
  </div>

  <div id='calendar_tab'></div>

  <div id='availability'>
    <% if !@employee.teacher.nil? %>
      <% if !@employee.teacher.availability.blank? %>
        <%= image_tag @employee.teacher.availability, width: '500' %>
      <% end %>
    <% end %>
  </div>
</div>