config/routes.rb
EliteApp::Application.routes.draw do
  resources :card_processing_upload_statuses do
    member do
      get :markings
      get :scanned
    end
  end

  resources :attendance_lists
  resources :card_processings
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'card/:student_ra/:exam_code', to: 'student_exams#card'
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'calendar/', to: 'calendar#index'

  get 'exam_executions/', to: 'exam_executions#index'
  get 'exam_executions/:exam_execution_id/result', to: 'exam_executions#result', as: 'result_exam_execution'
  get 'exam_executions/:exam_execution_id/attendance', to: 'exam_executions#attendance', as: 'attendance_exam_execution'
  get 'exam_executions/:exam_execution_id/cards', to: 'exam_executions#cards', as: 'cards_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned', to: 'exam_executions#scanned', as: 'scanned_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned_md5', to: 'exam_executions#scanned_md5', as: 'scanned_md5_exam_execution'

  resources :topics
  resources :card_types
  resources :student_exams do 
    member do 
      get :error
    end
  end
  get 'student_exams/new/', to: 'student_exams#new'

  resources :exam_answers
  resources :exams do
    collection do
      post :import
    end
  end 
  resources :questions
  resources :exam_cycles
  resources :applicants  do
    
  end
  resources :students do 
    member do 
      get :fix_ra
    end
    collection do
      post :import
    end
  end

  resources :poll_question_types
  resources :poll_question_categories
  resources :poll_pdfs
  resources :polls

  resources :teacher_absences
  resources :teacher_reports

  resources :klazz_calendars

  resources :personal_infos
  resources :professional_infos
  resources :schedule_infos

  resources :teachers do
    resources :periods, controller: 'teacher_periods'
  end
  resources :employees

  resources :absence_reasons
  resources :majors
  resources :school_roles
  resources :elite_roles
  resources :klazz_types
  resources :subjects
  resources :subject_threads

  resources :klazzes do 
    resources :periods, controller: 'klazz_periods'
  end
  
  resources :campuses do 
    resources :periods, controller: 'campuses_periods'
  end
  resources :super_klazzes 
  resources :product_years
  resources :years
  resources :products
  resources :product_groups
  resources :product_types

  get 'change_role/:role', to: 'role_sessions#update'

  match 'auth/google_oauth2/callback', to: 'employee_sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'login_as/:id', to: 'employee_sessions#update', as: 'login_as'
  match 'logout', to: 'employee_sessions#destroy', as: 'logout'

  get 'api/cards', to:'api#student_exams', as: 'api'
  get 'home', to: 'home#index', as: 'home'
  get "exam_results", to: 'exam_results#index'  
  root to: 'home#index'
end

app/models/super_klazz.rb
class SuperKlazz < ActiveRecord::Base
  
  attr_accessible :campus_id, :product_year_id

  belongs_to :campus
  belongs_to :product_year
  has_many :klazzes, dependent: :destroy

  has_many :exam_executions, dependent: :destroy
  has_many :student_exams, through: :exam_executions

  has_many :enrollments, dependent: :destroy
  has_many :enrolled_students, through: :enrollments, source: :student

  has_many :applicants, dependent: :destroy
  has_many :applicant_students, through: :applicants, source: :student

  validates :campus, :product_year, presence: true
  validates :product_year_id, uniqueness: { scope: :campus_id }
  
  def name
    label_method
  end
  
  def label_method
    product_year.name + ' - ' + campus.name
  end

  def product_year_name
    product_year.name
  end
end

app/controllers/super_klazzes_controller.rb
class SuperKlazzesController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @super_klazz.save
      redirect_to super_klazzes_path, notice: 'Super klazz was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @super_klazz.update_attributes(params[:super_klazz])
      redirect_to super_klazzes_path, notice: 'Super klazz was successfully updated.'
    else
      render :edit
    end
  end
end

app/views/super_klazzes/_form.html.erb
<%= simple_form_for(@super_klazz) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :product_year %>
    <%= f.association :campus %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/super_klazzes/edit.html.erb
<%= title 'Edit Super Klazz', 
  link_to('Show', @super_klazz),
  link_to('Back', super_klazzes_path) %>

<%= render 'form' %>

app/views/super_klazzes/index.html.erb
<%= title 'Super Turmas', 
  (link_to('Nova Super Turma', new_super_klazz_path) if can?(:create, SuperKlazz)) %>

<table id="super_klazzes" class="display is-datatable">
  <thead>
    <tr>
      <th>Name</th>
      <th>ProductYear</th>
      <th>Campus</th>
    </tr>
  </thead>

  <tbody>
  <% @super_klazzes.each do |super_klazz| %>
    <tr>
      <td>
        <%= super_klazz.name %>
        <span class='float-right'>
          <% if can?(:update, super_klazz) %>
            <%= link_to 'Editar', edit_super_klazz_path(super_klazz) %>
          <% end %>
        </span>
      </td>
      <td><%= super_klazz.product_year.name %></td>
      <td><%= super_klazz.campus.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/super_klazzes/new.html.erb
<%= title 'New Super Klazz', link_to('Back', super_klazzes_path) %>

<%= render 'form' %>

app/views/super_klazzes/show.html.erb
<%= title @super_klazz.name, 
  (link_to('Edit', edit_super_klazz_path(@super_klazz)) if can?(:update, @klazz)),
  link_to('Back', klazzes_path) %>

<div class='tabs'>
  <ul>
    <li><a href='#info_tab'>Info</a></li>
    <li><a href='#students_tab'>Students</a></li>
  </ul>

  <div id='info_tab' class='resource'>
    <p><span>Super Klazz: </span><%= @super_klazz.name %></p>
  </div>

    <div id='students_tab'>
      <table id="students" class="display is-datatable">
        <thead>
          <tr>
            <th>Name</th>
            <th>Ra</th>
            <th>Email</th>
          </tr>
        </thead>

        <tbody>
        <% @super_klazz.enrolled_students.each do |student| %>
          <tr>
            <td>
              <%= student.name %>
              <% if current_employee.admin? %>
                <span style='float: right;'>
                  <%= link_to 'Show', student_path(student) %> |
                  <%= link_to 'Edit', edit_student_path(student) %> |
                  <%= link_to 'Destroy', student, method: :delete, confirm: 'Are you sure?' %>
                </span>
              <% end %>
            </td>
            <td><%= student.ra %></td>
            <td><%= student.email %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>