config/routes.rb
EliteApp::Application.routes.draw do
  resources :card_processing_upload_statuses do
    member do
      get :markings
      get :scanned
    end
  end

  resources :attendance_lists
  resources :card_processings
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'card/:student_ra/:exam_code', to: 'student_exams#card'
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'calendar/', to: 'calendar#index'

  get 'exam_executions/', to: 'exam_executions#index'
  get 'exam_executions/:exam_execution_id/result', to: 'exam_executions#result', as: 'result_exam_execution'
  get 'exam_executions/:exam_execution_id/attendance', to: 'exam_executions#attendance', as: 'attendance_exam_execution'
  get 'exam_executions/:exam_execution_id/cards', to: 'exam_executions#cards', as: 'cards_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned', to: 'exam_executions#scanned', as: 'scanned_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned_md5', to: 'exam_executions#scanned_md5', as: 'scanned_md5_exam_execution'

  resources :topics
  resources :card_types
  resources :student_exams do 
    member do 
      get :error
    end
  end
  get 'student_exams/new/', to: 'student_exams#new'

  resources :exam_answers
  resources :exams do
    collection do
      post :import
    end
  end 
  resources :questions
  resources :exam_cycles
  resources :applicants  do
    
  end
  resources :students do 
    member do 
      get :fix_ra
    end
    collection do
      post :import
    end
  end

  resources :poll_question_types
  resources :poll_question_categories
  resources :poll_pdfs
  resources :polls

  resources :teacher_absences
  resources :teacher_reports

  resources :klazz_calendars

  resources :personal_infos
  resources :professional_infos
  resources :schedule_infos

  resources :teachers do
    resources :periods, controller: 'teacher_periods'
  end
  resources :employees

  resources :absence_reasons
  resources :majors
  resources :school_roles
  resources :elite_roles
  resources :klazz_types
  resources :subjects
  resources :subject_threads

  resources :klazzes do 
    resources :periods, controller: 'klazz_periods'
  end
  
  resources :campuses do 
    resources :periods, controller: 'campuses_periods'
  end
  resources :super_klazzes 
  resources :product_years
  resources :years
  resources :products
  resources :product_groups
  resources :product_types

  get 'change_role/:role', to: 'role_sessions#update'

  match 'auth/google_oauth2/callback', to: 'employee_sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'login_as/:id', to: 'employee_sessions#update', as: 'login_as'
  match 'logout', to: 'employee_sessions#destroy', as: 'logout'

  get 'api/cards', to:'api#student_exams', as: 'api'
  get 'home', to: 'home#index', as: 'home'
  get "exam_results", to: 'exam_results#index'  
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/_admin_links.html.erb
<div id='admin'>
  <div class='section'>
    <h2>Escola</h2>
    <div class='link'><%= link_to 'Anos', years_path %></div>
    <div class='link'><%= link_to 'Unidades', campuses_path %></div>
    <div class='link'><%= link_to 'Segmentos', product_types_path %></div>
    <div class='link'><%= link_to 'Produtos', product_years_path %></div>
    <div class='link'><%= link_to 'SuperTurmas', super_klazzes_path %></div>
    <div class='link'><%= link_to 'Turmas', klazzes_path %></div>
  </div>

  <div class='section'>
    <h2>Avaliações</h2>
    <div class='link'><%= link_to 'Ciclos', exam_cycles_path %></div>
    <div class='link'><%= link_to 'Provas', exams_path(is_bolsao: false) %></div>
    <div class='link'><%= link_to 'Calendário de Provas', exam_executions_path %></div>
    <div class='link'><%= link_to 'Arquivos Enviados', card_processings_path %></div>
    <div class='link'><%= link_to 'Resultados por dia', card_processing_upload_statuses_path %></div>
    <div class='link'><%= link_to 'Cartão-Resposta em Branco', new_student_exam_path(format: :pdf), :target => '_blank' %></div>
  </div>

  <div class='section'>
    <h2>Usuários</h2>
    <div class='link'><%= link_to 'Funcionários', employees_path %></div>
    <div class='link'><%= link_to 'Alunos', students_path %></div>
  </div>

</div>

app/views/home/_campus_head_teacher_links.html.erb
<div id="campus_head_teacher">
  <% if !current_employee.operator? %>
  <div class='section'>
    <h2>Geral</h2>
    <div class='link'><%= link_to 'Turmas', klazzes_path %></div>
    <div class='link'><%= link_to 'Unidades', campuses_path %></div>
    <div class='link'><%= link_to 'Alunos', students_path %></div>
  </div>
  <% end %>

  <div class='section'>
    <h2>Provas</h2>
    <div class='link'><%= link_to 'Calendário de Provas', exam_executions_path %></div>
    <% if !current_employee.operator? %>
    <div class='link'><%= link_to 'Arquivos enviados', card_processings_path %></div>
    <div class='link'><%= link_to 'Cartão-Resposta em Branco', new_student_exam_path(format: :pdf), :target => '_blank' %></div>
    <% end %>
  </div>
</div>

app/views/home/_campus_principal_links.html.erb
<div id="campus_principal">
  <%= link_to 'Klazzes', klazzes_path %><br />
  <%= link_to 'Teacher Absences', teacher_absences_path %>
</div>

app/views/home/_hr_links.html.erb
<div id="hr">
</div>

app/views/home/_product_head_teacher_links.html.erb
<div id="product_head_teacher">
  <%= link_to 'Klazzes', klazzes_path %><br />
</div>

app/views/home/_subject_head_teacher_links.html.erb
<div id="subject_head_teacher">
  <%= link_to 'Klazzes', klazzes_path %><br />
</div>

app/views/home/_teacher_links.html.erb
<div id="teacher">

<% if current_employee.teacher.updated_at < '2013-10-30'.to_date %>
<div class="bootstrapButton-green">
  <%= link_to 'Preencha a Pré-Disponibilidade 2014', edit_personal_info_path(current_employee), id: 'button_text' %>
</div>
<% else %>
<p>Obrigado por enviar a sua Pré-Disponibilidade para o ano de 2014!</p>
<p>Você poderá editá-la até o dia 15 de novembro utilizando o botão abaixo.</p>
<br/>
<div class="bootstrapButton">
  <%= link_to 'Edite sua Pré-Disponibilidade 2014', edit_personal_info_path(current_employee), id: 'button_text' %>
</div>
<% end %>

</div>

app/views/home/index.html.erb
<%= title 'Início' %>

<% unless current_role.nil? %>
  <%= render current_role + '_links' %>
<% end %>