config/routes.rb
EliteApp::Application.routes.draw do
  resources :card_processing_upload_statuses do
    member do
      get :markings
      get :scanned
    end
  end

  resources :attendance_lists
  resources :card_processings
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'card/:student_ra/:exam_code', to: 'student_exams#card'
  get 'card_processings/new/:exam_execution_id', to: 'card_processings#new'
  get 'calendar/', to: 'calendar#index'

  get 'exam_executions/', to: 'exam_executions#index'
  get 'exam_executions/:exam_execution_id/result', to: 'exam_executions#result', as: 'result_exam_execution'
  get 'exam_executions/:exam_execution_id/attendance', to: 'exam_executions#attendance', as: 'attendance_exam_execution'
  get 'exam_executions/:exam_execution_id/cards', to: 'exam_executions#cards', as: 'cards_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned', to: 'exam_executions#scanned', as: 'scanned_exam_execution'
  get 'exam_executions/:exam_execution_id/scanned_md5', to: 'exam_executions#scanned_md5', as: 'scanned_md5_exam_execution'

  resources :topics
  resources :card_types
  resources :student_exams do 
    member do 
      get :error
    end
  end
  get 'student_exams/new/', to: 'student_exams#new'

  resources :exam_answers
  resources :exams do
    collection do
      post :import
    end
  end 
  resources :questions
  resources :exam_cycles
  resources :applicants  do
    
  end
  resources :students do 
    member do 
      get :fix_ra
    end
    collection do
      post :import
    end
  end

  resources :poll_question_types
  resources :poll_question_categories
  resources :poll_pdfs
  resources :polls

  resources :teacher_absences
  resources :teacher_reports

  resources :klazz_calendars

  resources :personal_infos
  resources :professional_infos
  resources :schedule_infos

  resources :teachers do
    resources :periods, controller: 'teacher_periods'
  end
  resources :employees

  resources :absence_reasons
  resources :majors
  resources :school_roles
  resources :elite_roles
  resources :klazz_types
  resources :subjects
  resources :subject_threads

  resources :klazzes do 
    resources :periods, controller: 'klazz_periods'
  end
  
  resources :campuses do 
    resources :periods, controller: 'campuses_periods'
  end
  resources :super_klazzes 
  resources :product_years
  resources :years
  resources :products
  resources :product_groups
  resources :product_types

  get 'change_role/:role', to: 'role_sessions#update'

  match 'auth/google_oauth2/callback', to: 'employee_sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'login_as/:id', to: 'employee_sessions#update', as: 'login_as'
  match 'logout', to: 'employee_sessions#destroy', as: 'logout'

  get 'api/cards', to:'api#student_exams', as: 'api'
  get 'home', to: 'home#index', as: 'home'
  get "exam_results", to: 'exam_results#index'  
  root to: 'home#index'
end

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base
  attr_accessible :name

  has_many :products
  has_many :product_group_preferences
  has_many :teachers_with_preference, through: :product_group_preferences, source: :teacher

  validates :name, presence: true, uniqueness: true
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def edit
  end

  def create
    if @product_group.save
      redirect_to product_groups_url, notice: 'Product group was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @product_group.update_attributes(params[:product_group])
      redirect_to product_groups_url, notice: 'Product group was successfully updated.'
    else
      render 'edit'
    end
  end
end

app/views/product_groups/_form.html.erb
<%= simple_form_for(@product_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_groups/edit.html.erb
<%= title 'Edit Product Group',
  link_to('Back', product_groups_path) %>

<%= render 'form' %>

app/views/product_groups/index.html.erb
<%= title 'Product Groups', link_to('New Product Group', new_product_group_path) %>

<table id='product_groups' class='display is-datatable'>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
  <% @product_groups.each do |product_group| %>
    <tr>
      <td>
        <%= product_group.name %>
        <%= link_to 'Edit', edit_product_group_path(product_group), class: 'float-right' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/product_groups/new.html.erb
<%= title 'New Product Group',
  link_to('Back', product_groups_path) %>

<%= render 'form' %>